//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GHE_TRONG_PHONG
    {
        public int MAGHE { get; set; }
        public int MAPHONG { get; set; }
        public string TRANGTHAI { get; set; }
        public int MA { get; set; }
    
        public virtual TB_GHE TB_GHE { get; set; }
        public virtual TB_PHONG TB_PHONG { get; set; }
    }
}
