//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LICHCHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_LICHCHIEU()
        {
            this.TB_VEXEMPHIM = new HashSet<TB_VEXEMPHIM>();
        }
    
        public int MALICHCHIEU { get; set; }
        public System.DateTime NGAYCHIEU { get; set; }
        public System.DateTime NGAYKETTHUC { get; set; }
        public int MAPHONG { get; set; }
        public int MAPHIM { get; set; }
    
        public virtual TB_PHIM TB_PHIM { get; set; }
        public virtual TB_PHONG TB_PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VEXEMPHIM> TB_VEXEMPHIM { get; set; }
    }
}
