//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_NHANVIEN()
        {
            this.TB_TAIKHOAN = new HashSet<TB_TAIKHOAN>();
        }
    
        public int MANHANVIEN { get; set; }
        public string TENNHANVIEN { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string CMTND { get; set; }
        public System.DateTime NGAYVAOLAM { get; set; }
        public string QUEQUAN { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string GIOITINH { get; set; }
        public string ANH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TAIKHOAN> TB_TAIKHOAN { get; set; }
    }
}
