//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWebFilm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_NHANVIEN()
        {
            this.TB_TAIKHOAN = new HashSet<TB_TAIKHOAN>();
        }
        [Display(Name="Mã nhân viên")]
        public int MANHANVIEN { get; set; }
        [Display(Name = "Tên nhân viên")]

        public string TENNHANVIEN { get; set; }
        [Display(Name = "Ngày sinh")]

        public System.DateTime NGAYSINH { get; set; }

        public string CMTND { get; set; }
        [Display(Name = "Ngày vào làm")]

        public System.DateTime NGAYVAOLAM { get; set; }
        [Display(Name = "Quê quán")]

        public string QUEQUAN { get; set; }
        [Display(Name = "Địa chỉ")]

        public string DIACHI { get; set; }
        [Display(Name = "Sô diện thoại")]

        public string SDT { get; set; }
        [Display(Name = "Giới tính")]

        public string GIOITINH { get; set; }
        [Display(Name = "Ảnh")]

        public string ANH { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TAIKHOAN> TB_TAIKHOAN { get; set; }
    }
}
