//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PHIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PHIM()
        {
            this.TB_LICHCHIEU = new HashSet<TB_LICHCHIEU>();
        }
    
        public int MAPHIM { get; set; }
        public string QUOCGIA { get; set; }
        public string HINHANH { get; set; }
        public string MOTAPHIM { get; set; }
        public int THOILUONG { get; set; }
        public string TENPHIM { get; set; }
        public int MALOAIPHIM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LICHCHIEU> TB_LICHCHIEU { get; set; }
        public virtual TB_LOAIPHIM TB_LOAIPHIM { get; set; }
    }
}
