//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PHONG()
        {
            this.TB_LICHCHIEU = new HashSet<TB_LICHCHIEU>();
            this.TB_GHE_TRONG_PHONG = new HashSet<TB_GHE_TRONG_PHONG>();
        }
    
        public int MAPHONG { get; set; }
        public int SOPHONG { get; set; }
        public int SOGHE { get; set; }
        public string LOAIPHONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LICHCHIEU> TB_LICHCHIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_GHE_TRONG_PHONG> TB_GHE_TRONG_PHONG { get; set; }
    }
}
