//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_THEKHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_THEKHACHHANG()
        {
            this.TB_VEXEMPHIM = new HashSet<TB_VEXEMPHIM>();
        }
    
        public int MATHEKHACHHANG { get; set; }
        public string TENKHACHHANG { get; set; }
        public string CMTND { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public System.DateTime NGAYDANGKY { get; set; }
        public string MUCDOTHANTHIET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VEXEMPHIM> TB_VEXEMPHIM { get; set; }
    }
}
