//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TAIKHOAN()
        {
            this.TB_VEXEMPHIM = new HashSet<TB_VEXEMPHIM>();
        }

        public TB_TAIKHOAN(string tENDANGNHAP, string lOAITAIKHOAN, string mATKHAU, int mANHANVIEN)
        {
            TENDANGNHAP = tENDANGNHAP;
            LOAITAIKHOAN = lOAITAIKHOAN;
            MATKHAU = mATKHAU;
            MANHANVIEN = mANHANVIEN;
        }

        public int MATAIKHOAN { get; set; }
        public string TENDANGNHAP { get; set; }
        public string LOAITAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public int MANHANVIEN { get; set; }
    
        public virtual TB_NHANVIEN TB_NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VEXEMPHIM> TB_VEXEMPHIM { get; set; }
    }
}
