//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VEXEMPHIM
    {
        public int MAVE { get; set; }
        public int GIAVE { get; set; }
        public int MATAIKHOAN { get; set; }
        public int MALICHCHIEU { get; set; }
        public int MATHEKHACHHANG { get; set; }
        public System.DateTime NgayLap { get; set; }
    
        public virtual TB_LICHCHIEU TB_LICHCHIEU { get; set; }
        public virtual TB_TAIKHOAN TB_TAIKHOAN { get; set; }
        public virtual TB_THEKHACHHANG TB_THEKHACHHANG { get; set; }
    }
}
